### ISSUE TITLE
Items in analyzer don't stack

### ISSUE THREAD

**Issue by zenieldanaku** [FossilsArcheologyRevival/FossilsArcheology1.7#217]
Build 7.2
When analyzing fossils, the analyzer sometimes returns bone meal, or sand, but it doesn't stack these items, even when, in the player's inventory, they do stack. Similarly, the big inventory slot, that is above the others smaller three, should only contain the actual DNA, while the other slots should get the other, "trash-like" items (sand, coal, bone meal, etc).

**Comment by zenieldanaku** [comment]
I'd suggest a total rework of the Analizer's GUI: one space on the left, to put the items to analyze in, and a 3x3 grid on the right to place the returned items.

**Comment by zenieldanaku** [comment]
Is this too hard to solve or it is just being ignored?

**Comment by Alex-the-666** [comment]
@iLexiconn  ^

**Comment by Alex-the-666** [comment]
It was fixed and will be in 7.3
