### ISSUE TITLE
Baby dodos and mammoths have twitchy head movement

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheology1.7#271]

**Comment by lindstheginj** [comment]
+ allosaurus

**Comment by lindstheginj** [comment]
plus adult dodos and baby ankys

**Comment by lindstheginj** [comment]
I THINK I FIGURED IT OUT. Its when they're trying to attack something that it gets twitchy

**Comment by lindstheginj** [comment]
Nvm happens regardless. Add brachi baby and adult there too

**Comment by Alex-the-666** [comment]
Has to do with attack sytem

**Comment by Alex-the-666** [comment]
@gegy1000 , this has to do with getAttackBounds() in EntityPrehistoric not working.
