### ISSUE TITLE
Allosaurus Egg name

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheology1.7#274]
![2016-07-02_21 36 27](https://cloud.githubusercontent.com/assets/15497127/16543330/234af11c-409d-11e6-8d58-96d389a35fc2.png)

**Comment by Alex-the-666** [comment]
please post this in the localization that 4F STILL HASN'T UPDATED... @4f6f3b

**Comment by lindstheginj** [comment]
I don't know what that means :B
