### ISSUE TITLE
weaponshop spawns weird

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheology1.7#299]
![2016-07-03_21 36 50](https://cloud.githubusercontent.com/assets/15497127/16548907/4a99a334-4166-11e6-8b3b-65e83e1931b1.png)

**Comment by lindstheginj** [comment]
![2016-07-03_21 38 16](https://cloud.githubusercontent.com/assets/15497127/16548917/76ffd5ec-4166-11e6-8dd1-cc8ad05974c2.png)

**Comment by Alex-the-666** [comment]
inpossible to fix without dropping spawnrates
