### ISSUE TITLE
When you ride spinos out of the water, they remain in swimming position

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheology1.7#325]
![2016-07-07_20 12 15](https://cloud.githubusercontent.com/assets/15497127/16673768/24afcfce-447f-11e6-8713-be83dadb750d.png)

**Comment by crakiMDH** [comment]
Thats rather strange, Spinos switch positions just fine for me...

**Comment by lindstheginj** [comment]
That's because it was fixed before the update was released.

**Comment by ethanwait25** [comment]
Lol if it was closed 7 days ago, before the update, it's not an issue.
