### ISSUE TITLE
After being killed by rex, you can't touch him

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheology1.7#327]
This doesn't happen 100% of the time but it has happened twice. I get killed by rex, respawn, go to hit him again, and nothing. Can't hit him. Try to use dinopedia? Doesnt work either.

**Comment by lindstheginj** [comment]
Happened to spino too

**Comment by Alex-the-666** [comment]
just an old relog issue.
