### ISSUE TITLE
Plesiosaurus doesnt fight back

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheology1.7#329]
I looked at entityplesiosaurus and can only assume that since it has a line about attack.animation, it should be attacking me... but it doesnt even follow me

**Comment by Alex-the-666** [comment]
every animal has attack animations. even the dodos. Don't look at code and say XYZ is missing so it has to be done, as somethings have multiple uses. Also they shouldn't attack.
