### ISSUE TITLE
When mobs that pick you up attack you, you have the option to L Shift to dismount

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheology1.7#331]
This is either a glitch or an escape method, I don't know which but its safer to report it. Plus the mount health shows up, like a horse. Its weird

**Comment by Alex-the-666** [comment]
It's impossible to fix without doing ASM, something that is...
1. buggy with other mods
2.crashy AF

**Comment by gegy1000** [comment]
You could cancel the Mount event
