### ISSUE TITLE
Triceratops just shakes his head at you instead of attacking.

### ISSUE THREAD

**Issue by Alex-the-666** [FossilsArcheologyRevival/FossilsArcheology1.7#334]
Just like the old issue.

**Comment by crakiMDH** [comment]
Actually, the Trike shakes their heads because they are going "You screwed up son.. *shakes head* I'll kill you when the A.I to let me do so happens... BTW this is a joke xD

**Comment by 4f6f3b** [comment]
Hey craki, the Github issues page is for reporting bugs, please don't post off-topic responses. There is an entire forum thread already dedicated to general discussion for the mod on minecraftforum.net.
