### ISSUE TITLE
Incompatiblity with CoFHCore

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheology1.7#342]
http://pastebin.com/TC3pytVp

**Comment by Sunconure11** [comment]
Mod responsible is CoFHCore

http://minecraft.curseforge.com/projects/cofhcore

**Comment by gegy1000** [comment]
Can you send fml-client-latest.log in .minecraft/logs please?

**Comment by Sunconure11** [comment]
Heres one from a clean slate that has just F&A, CoFHCore, and LLibrary. It still crashes with the same error.

http://pastebin.com/Cn6fb3RR

**Comment by iLexiconn** [comment]
Can you also send me a zipped version of `llibrary/debug` please? (it;s inside the minecraft directory)

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/ys2jl61f7rrkzxj/debug.zip?dl=0

**Comment by iLexiconn** [comment]
CoFHCore really messes with stuff then. This is what it normally contains: http://i.imgur.com/06WOjr8.png

**Comment by Sunconure11** [comment]
Is there anything that can be done on either end then? Quite a few popular mods use it, and some people like myself use it for ore generation.

**Comment by Alex-the-666** [comment]
Yeah this is a real big issue; I never expected so many people to use CoFH core.

**Comment by Sunconure11** [comment]
Thermal Expansion requires it. So yeah, a lot of people are using it.

**Comment by pchard** [comment]
So.. How to proceed? Wait for a bug fix?

**Comment by gegy1000** [comment]
Yes.
