### ISSUE TITLE
Pteranodon won't fly

### ISSUE THREAD

**Issue by ErikC17Minecraft** [FossilsArcheologyRevival/FossilsArcheology1.7#348]
The pteranodons won't fly. If use a lead and "drag" the in to the sky the females start to fly and sometimes walk like they do on the ground while the male won't fly at all (the male is only focusing on the females)

**Comment by Alex-the-666** [comment]
They fly. Go out of flatland so they can gain air.

**Comment by crakiMDH** [comment]
Well... config has a allow flying thing. If set to true, and if the conditions are met in-game, the Pteranodon will fly.
