### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by pchard** [FossilsArcheologyRevival/FossilsArcheology1.7#353]
Hey.

Trying to update Fossils and Archeology Revival on my modpack (Jurassic World: Revelations) but I get this error:

Crash Log: https://gist.github.com/pchard/609adc07d80915fe19b5f49617617687

fml-client-latest.log: https://gist.github.com/pchard/99a58d2e6157548058eac0ecd8e1369c

I don't really know what causes it, and I really need help.

**Comment by 4f6f3b** [comment]
See this. https://github.com/FossilsArcheologyRevival/FossilsArcheology1.7/issues/342
