### ISSUE TITLE
Accuracy tidbits

### ISSUE THREAD

**Issue by PCAwesomeness** [FossilsArcheologyRevival/FossilsArcheology1.7#358]
- [x] Sarcosuchus is mentioned as unable to perform a death roll in the DinoPedia. It's able to 
perform one in-game, anyways.
- [x] Ankylosaurus also has a segregation between its biological information and its in-game depiction. In the Dino-Pedia, it's said to be 6 meters long. In the game, it's 10.
- [ ] [One extremely overlooked study says that Allosaurus couldn't use its head as an axe to slaughter prey, as it would break all its teeth in the process; as well as this, it had the sufficient bite force to pull off a more traditional method of attack.](http://digital.csic.es/bitstream/10261/22490/1/102.pdf)
- [x] [Another overlooked study says that the tallest a Titanis could get was 1.9 meters, rather than the 2.5 meters we've all been accustomed to. (This should also be fixed in the DinoPedia.)](http://www.flmnh.ufl.edu/files/6313/9447/0040/bulletin-gouldquitmyerlowres.pdf)
 - [x] As well as this, Phorusrhacos and Kelenken are a little oversized; in real life, they approached heights of 2.4 and 3 meters respectively. (Again, their sizes should also be updated in the DinoPedia.)

**Comment by crakiMDH** [comment]
wat.

How did you measure the height of the Phorusrhacos and the Kelenken without them taking off to eat some prey?

**Comment by PCAwesomeness** [comment]
@crakiMDH 

1: Dude, did you even read the paper...
2: Honestly, if we use the proportions of other phorusrhacines, then a 3 meter tall Kelenken is likely.
