### ISSUE TITLE
Plesiosaurus too small

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheology1.7#361]
When I spawned in the Plesiosaurus, I noticed that its way to small. Perhaps its "adult" form is stuck in a certain growth?
![2016-07-12_23 24 08](https://cloud.githubusercontent.com/assets/16602481/16791809/112ab1e6-4888-11e6-82b3-8a462205f6e2.png)

Isn't the Plesiosaurus in the image to small?

**Comment by lindstheginj** [comment]
Hardly. Plesiosaurus only grew to around 3.5 meters.

**Comment by crakiMDH** [comment]
oh... Wait a minute! Maybe because they actually gave it a species, they had to resize it to match that species! That makes sense! Because the Plesiosaur could've been an Elasmosaurus. Thanks for the info!
