### ISSUE TITLE
Config not working.

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheology1.7#362]
I was adjusting the mods config. I turned off all feathers, and I also set to false breeding, starving, and that. However, I saw a baby Triceratops in a pen that I didn't create, and the dinosaurs don't stop eating. The feathers were by default set to false, yet the dinosaurs with feathers had them for no reason. I don't know if block breaking is also glitching, because all the enclosures have iron in their walls. Please help me, I want to play the mod like before.

**Comment by lindstheginj** [comment]
All of these issues have already been closed (read as: solved). When 7.3.1 is released, download that and it should fix all your issues.
