### ISSUE TITLE
Male Dinosaurs (or at least Velociraptors) can lay eggs.

### ISSUE THREAD

**Issue by Mushroomsock** [FossilsArcheologyRevival/FossilsArcheology1.7#364]
Was putting a male Velociraptor into a nest when suddenly an egg popped out. DinosLayEggsLikeChickens is enabled.

**Comment by Alex-the-666** [comment]
He's just transgender, no issue here

**Comment by crakiMDH** [comment]
There are transgender dinosaurs?!
