### ISSUE TITLE
Spinosaurus Attack Loop

### ISSUE THREAD

**Issue by Pedecto** [FossilsArcheologyRevival/FossilsArcheology1.7#365]
I was curious about spinosaurus' attack damage, so I plopped one down on a flatworld map and hit it. Due to the obnoxious slime spawns, I had it set to peaceful difficulty. 
Turns out that it can't kill you on peaceful. Ever. Pressing shift to dismount doesn't work either; you just cause spino to play the shaking animation again. Switching to creative mode allows you to escape, presumably because he is no longer hostile. Additionally, switching to a higher difficulty will cause him to kill you as intended. I doubt I'll ever encounter this issue in actual gameplay, but it's an issue nonetheless. I'm not sure if this can be reproduced with other similar creatures, but it's likely.

**Comment by Alex-the-666** [comment]
No mobs can kill you on peaceful. End of story. Not something we can fix.
