### ISSUE TITLE
"Nocturnal" animals don't sleep during the day

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheology1.7#367]
When I'm playing the mod, I've noticed that the dinopedia states that Velociraptor and Deinonychus are nocturnal. However, I haven't seen Deinos or Raptors sleeping when all the other animals are awake during the day. I'm supposing this is a bug.

**Comment by lindstheginj** [comment]
They do sleep during the day, they just require shade to do so.

**Comment by crakiMDH** [comment]
oh.. Thanks!
