### ISSUE TITLE
Deinos and raptors glitch

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheology1.7#368]
When the Deinos and Raptors use their awesome attack animation on animals such as sheeps, they kill the mob and then glitch off in the ground. They just turn a shade of black and sink to it.

**Comment by Alex-the-666** [comment]
Vanilla dismounting issue. try reloging.

**Comment by crakiMDH** [comment]
Wait what is the vanilla dismoutning issue?
