### ISSUE TITLE
Piping in veggies with Buildcraft pipes puts it in the wrong slot.

### ISSUE THREAD

**Issue by darthvader45** [FossilsArcheologyRevival/FossilsArcheology1.7#370]
I've been trying to automate herbivore feeding, but it seems the feeders no longer work as intended when it comes to automation.  I can automate meat just fine, but when I try to pipe in wheat and other veggies, it gets put in the meat slot and backs up there.

**Comment by darthvader45** [comment]
Screenshot is attached.

![2016-07-13_13 49 01](https://cloud.githubusercontent.com/assets/2816420/16815202/e5f3bf7a-4906-11e6-8d62-1a0c0b7a3933.png)

**Comment by crakiMDH** [comment]
I have my doubts that they will fix this... After all, they fix bugs related to their mod. They don't own Buildcraft, so I don't think they can fix the bug if buildcraft causes it.

**Comment by Mushroomsock** [comment]
This happens with vanilla Hoppers too.

**Comment by iLexiconn** [comment]
https://github.com/FossilsArcheologyRevival/FossilsArcheology1.7/issues/359

**Comment by Alex-the-666** [comment]
^ is for analyzer. This is the feeder.

**Comment by darthvader45** [comment]
Honestly, it really needs to be fixed.  I'd like to be able to automate feeders for my herbivores.  I'll try testing with Itemducts from TE and transfer pipes from extra utilities and see if those do the same.

**Comment by darthvader45** [comment]
Thank you.
