### ISSUE TITLE
Smilodon mouth animation

### ISSUE THREAD

**Issue by Pedecto** [FossilsArcheologyRevival/FossilsArcheology1.7#372]
Occasionally, but not always, smilodon's eating/drinking/vocal animation loops for an abnormally long time. This has actually superseded the sleeping animation in some cases, leaving the poor animal stuck opening and closing its mouth while standing for the entire night. There's a feeder and water blocks in the area, not sure which triggers the problem.

**Comment by lindstheginj** [comment]
Considering that mobs don't drink, I would think that it would be the feeder. We are having a few other little problems with feeders, so I personally wouldn't rule it out. However, I'm no coder so don't take my schist for granite :B

**Comment by Pedecto** [comment]
thought they said something about adding drinking animations. Oh well, that just rules out one option.

**Comment by Alex-the-666** [comment]
no, no, no, no. just an animation issue, which is super rare. leave the chunk, relog, then come back. fixed it happening to my confuciusornis.
