### ISSUE TITLE
Any mob save for Sarco does not attack while being ridden.

### ISSUE THREAD

**Issue by Dakotsie** [FossilsArcheologyRevival/FossilsArcheology1.7#383]
Sacros are definitely one of the few, if not, the only creature that will actively attack things that the player has attacked, or has attacked the player while being ridden. Not sure if this is intended, but if it is not intended, I'd actually like to see this "feature" extended to the other mobs. It's very fun to use the Sarco as a war mount, like a tank... Can't do it on my rex though. ;-;

**Comment by crakiMDH** [comment]
Well, as I see it, the dino would have to be focused on giving you a steady mount. Some of them would have to lean down to attack, and that could make you or your items topple off. However, when you ride the Sarco you are flat, and its mouth is in a level that they can attack. So its logical that the Sarco can be ridden and attack, cause its position wouldn't make you fall off. BTW I'm not a mod, I'm just giving u tips & stuff.

**Comment by Dakotsie** [comment]
No, from what I understand, all dinos are supposed to attack while being ridden, but they don't. I sounded unsure in the original post, but after talking to a dev, they are supposed to attack.
