### ISSUE TITLE
Mobs that are sitting become unresponsive upon reloading a singleplayer world.

### ISSUE THREAD

**Issue by Dakotsie** [FossilsArcheologyRevival/FossilsArcheology1.7#385]
If any mobs are left sitting in singleplayer, upon reloading the world, they become unresponsive. They still stand up, but do not move, even if ridden. A fix is to put them to follow or free roam and reload the world, which sometimes takes 2 or 3 tries to get them unstuck, but 1 time should fix it most of the time.

**Comment by Alex-the-666** [comment]
Intended - you aren't supposed to ride sitting dinosaurs.

**Comment by Dakotsie** [comment]
Might have already fixed this, but it is valid. You read the description wrong. Why you gatta make me look like a scrub reporter? I cri evry tiem. ;-;

**Comment by PinkSalamander** [comment]
I agree this is Valid

**Comment by PinkSalamander** [comment]
I agree this is valid I have the same issue my dinosaur go into the stay position and just refuse to move
