### ISSUE TITLE
Sturgeon spawn rate is absurd

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheology1.7#390]
https://www.dropbox.com/s/66gl85dtpq5ez0u/Screenshot%202016-07-14%2004.41.47.png?dl=0

https://www.dropbox.com/s/y7u0cfq78ubg19h/Screenshot%202016-07-14%2004.42.28.png?dl=0

**Comment by crakiMDH** [comment]
In the first picture it shows just 1, I think. And then in the second picture it shows like... 6? I don't know whats so absurd about it. You need to explain xD.

BTW I'm not a moderator, I'm giving u tips.

**Comment by Alex-the-666** [comment]
invalid, it's the same as squids.

**Comment by Sunconure11** [comment]
I'm posting here again because there might be something that can be done. Is it possible to handle fish spawning differently?

https://www.dropbox.com/s/xa9fbzxly995zox/Screenshot%202016-07-24%2012.21.55.png?dl=0
