### ISSUE TITLE
Names of all blocks are displayed as question mark.

### ISSUE THREAD

**Issue by vrnRaptor** [FossilsArcheologyRevival/FossilsArcheology1.7#391]
After the restart of the game, names of all blocks are displayed as question mark. I use russian localization.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2398119-fossils-and-archeology-revival-build-7-3-the?page=344#c7084
To repeat:
1. Run the game with Fossils and Archeology Revival Build 7.3.
2. Select russian localization.
3. Create a world.
4. Restart the game.
5. Now all the objects with question marks.

**Comment by iLexiconn** [comment]
Move issue to https://github.com/FossilsArcheologyRevival/FossilsArcheologyLocalizations
