### ISSUE TITLE
Hell Boats are taking over the nether

### ISSUE THREAD

**Issue by KawiiEssence** [FossilsArcheologyRevival/FossilsArcheology1.7#396]
![2016-07-14_10 48 05](https://cloud.githubusercontent.com/assets/20460977/16844091/bba92dda-49b1-11e6-9cbc-8776b64aec6d.png)
As you can see in this picture, there is a line of ships and it continues on for hundreds of blocks, the entire nether is filled with these and i feel they should definitely be made more rare.

**Comment by ethanwait25** [comment]
That's how I feel the archaeology tents and tar puts are. In my world, there's another tent every fifteen or twenty blocks.

**Comment by Alex-the-666** [comment]
This was already reported and fixed.
