### ISSUE TITLE
Arrows sometimes get stuck in mobs, continually damaging the mob it is in.

### ISSUE THREAD

**Issue by Dakotsie** [FossilsArcheologyRevival/FossilsArcheology1.7#400]
Easiest way to reproduce this is to spawn a rex, tame it, have it sit down, and then spam arrows from directly above the creature while in creative mode. This is a really minor issue though, as moving the mob away will stop the bug, and because most people won't be flying above their dino in creative while spamming arrows. Then again, I have spammed arrows in survival, so it might still happen occasionally. Even creatures who arrows normally bounce off of can experience this bug.

**Comment by Alex-the-666** [comment]
issue with big bounding boxes.
